### PR TITLE
Added polish translation of "webgl-2d-translation" article

### PR DESCRIPTION
**Pull request by vinci-mz**
Hello,
i've just added a new polish translation of "webgl-2d-translation" article.
I hope it's ready to pull.
I've published it https://vinci.org.pl/ref/podstawy-webgl/przesuniecia-dwuwymiarowe-w-webgl
Kind regrads,

### CODE REVIEW

**Comment by greggman** [comment]
Thanks!!!

**Comment by vinci-mz** [comment]
Hello,
I've started to translate "webgl-2d-rotation" and I've found as follows:

> You can see that as we rotate that point clockwise to the right the X value gets bigger and the Y gets smaller. If kept going past 90 degrees X would start getting smaller again and Y would start getting bigger.

I suppose the second sentence should be rather like:

>  If kept going past 90 degrees X would start getting smaller again and Y would still getting smaller too.

How do you think?

**Comment by greggman** [comment]
Hello :D

Maybe the definition of bigger / smaller is different in polish (or in my
head)?  At 90 degrees in the example Y = 0, As you go past 90 degrees Y
goes to -1. Its "magnitude" is bigger.  0 being the smallest magnitude

-gregg

**Comment by vinci-mz** [comment]
Hello,
I've decided to translate the phrase "Y would start getting bigger" as "Y would start getting negative values", because I was affraid a little misunderstanding in this place.  I hope this description may be more clear for people who usually compare numbers with signs and it is still true, isn't it?
Translation is published on  https://vinci.org.pl/ref/podstawy-webgl/obroty-dwuwymiarowe-w-webgl
I've created a new pull request too.

**Comment by greggman** [comment]
Yes that sounds fine

**Pull request merged**
