### PR TITLE
Fixed typo in webgl-utils.js createUniformSetters of 'tetxure' => 'te…

### PR DESCRIPTION
**Pull request by SimHacker**
…xture' that would cause problems binding arrays of SAMPLER_2D or SAMPLER_CUBE.

### CODE REVIEW

**Comment by SimHacker** [comment]
I live the way I type: fast with a lot of mistakes.

**Comment by greggman** [comment]
thanks!

**Comment by greggman** [comment]
FYI: You might want to consider using [twgl.js](http://twgljs.org).

**Comment by SimHacker** [comment]
Thank you! Yes, I just discovered that twgl.js library, and now I’m using it instead of webgl-utils.js, and it works great! The typo had even been corrected in the twgl code. (I read over that too — my intention is to really understand what’s going on, not just use a black box.) 

I had a real head banger for a while when I created my own framebuffer, and no matter what I did, nothing displayed. I finally took out the framebuffer creation code and it worked fine! I was unclear on the concept that WebGL already gave me a framebuffer for free, and by creating my own, it drew off screen. 

I’m making a WebGL version of my cellular automata machine emulator (which was inspired by Toffoli and Margolus’s book, "Cellular Automata Machines: A New Environment for Modeling”, but does a lot more now since it’s software). 

All the rules and rendering and drawing are currently implemented in straightforward unoptimized JavaScript, but it still runs pretty fast! So I can’t wait to see how fast it runs using WebGL shaders! First I’m making a shader to render the tiles, then I'm implement some of the CA rules and drawing tools as shaders.

I hope I can implement it in such a way that the JavaScript rules and shader rules share the same memory and infrastructure (for drawing into the cells, analyzing the histogram, etc). I’m storing the cells in a Uint8Array/ArrayBuffer, with a 1-pixel gutter around the edge for pre-wrapping or pre-clamping the edges, so the code doesn’t need to worry about that (although WebGL will do that automatically if it’s a power of 2). I hope I can just point a WebGL texture at it, and share the same memory between WebGL and JavaScript (applying the drawing tools and computing the histogram between frames), without copying it all the time. The tile engine will probably have to know about skipping over the gutter, but that’s easy. Come to think of it, the shader could computer a histogram, and render the drawing tools, too. But I’d like to see if I can support a hybrid approach so all the existing stuff keeps working, if possible. 

http://www.donhopkins.com/home/CAM6 <http://www.donhopkins.com/home/CAM6>

https://github.com/SimHacker/CAM6 <https://github.com/SimHacker/CAM6>

https://github.com/SimHacker/CAM6/blob/master/javascript/CAM6.js <https://github.com/SimHacker/CAM6/blob/master/javascript/CAM6.js>

// This code originally started life as a CAM6 simulator written in C
// and Forth, based on the original CAM6 hardware and compatible with
// the brilliant Forth software developed by Toffoli and Margolus. But
// then it took on a life of its own (not to mention a lot of other CA
// rules), and evolved into supporting many other cellular automata
// rules and image processing effects. Eventually it was translated to
// C++ and Python, and then more recently it has finally been
// rewritten from the ground up in JavaScript.
//
// The CAM6 hardware and Forth software for defining rules and
// orchestrating simulations is thoroughly described in this wonderful
// book by Tommaso Toffoli and Norman Margolus of MIT.
//
// Cellular Automata Machines: A New Environment for Modeling
// Published April 1987 by MIT Press. ISBN: 9780262200608.
// http://mitpress.mit.edu/books/cellular-automata-machines
// http://books.google.com/books?id=HBlJzrBKUTEC&printsec=frontcover
// http://www.researchgate.net/publication/44522568_Cellular_automata_machines__a_new_environment_for_modeling__Tommaso_Toffoli_Norman_Margolus

-Don

**Comment by SimHacker** [comment]
By the way: your charts comparing twgl calls to all the WebGL calls they produced were very helpful in understanding how WebGL (and your library) work! 

Also the Chrome WebGL inspector was great for comparing the state and sequences of calls and buffers of your demo app that did work with mine that didn’t. 

That’s how I finally got to the bottom of my framebuffer problem. By comparing your working demo with my broken version, I noticed that the states only differed in the RENDERBUFFER_BINDING being non-null for the one that didn’t work because I was creating my own offscreen framebuffer! (Old code left over from cargo cult programming.) Having a stupid head-banger problem like that forced me to go over everything with a fine tooth comb, which was a good exercise to ̀ do anyway.

Thanks! The twgl library is just what I need for the CA stuff, because I want to work with WebGL most directly and efficiently, and understand how it works on its own terms, but I don’t want to write a lot of repetitive boiler plate code. I might use a higher level 3d library like three.js later on, but twgl is perfect for my CA stuff and learning WebGL itself. 

-Don

**Pull request merged**
